[package]
name = "ethaddrgen"
version = "0.1.0"
authors = ["Jakub HlusiÄka <limeth@protonmail.com>"]

[dependencies]
itertools = "0.6.0"
rand = "0.3.15"
regex = "0.2.2"
secp256k1 = "0.6.2"
tiny-keccak = "1.2.1"
num_cpus = "1.5.0"
